name: Build & Deploy


on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pre-Registration-API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            mkdir test
            cd test
            echo 'Deployment successfull to server'