name: Build & Deploy


on:
  push:
    branches: [new-prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pre-Registration-API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            cd OtakuStan/Pre-Registration-API
            git pull origin main
            
            echo 'Killing the running containet'
            docker kill ${{secrets.CONTAINER_NAME}}

            echo 'Removing everything from machine'
            docker system prune -f

            echo 'Building the container'
            docker build -t ${{secrets.CONTAINER_NAME}} .

            echo 'Running the container'
            docker run -p 5000:5000 -e PORT=5000 -e NOTION_API_KEY=${{secrets.NOTION_API_KEY}} -e DATABASE_ID=${{secrets.DATABASE_ID}} -e NOTION_USER_ID=${{secrets.NOTION_USER_ID}} -e NOTION_USER_EMAIL=${{secrets.NOTION_USER_EMAIL}} -e EMAIL_AUTH=${{secrets.EMAIL_AUTH}} -e EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}} -e DISCORD_URI=${{secrets.DISCORD_URI}} -d ${{secrets.CONTAINER_NAME}}

            echo 'Sucessfully deployed to server'